name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]
  # ou pour déclenchement manuel :
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*' 'node_modules/*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: freemindvision
        environment_name: Freemindvision-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip